# This workflow will do a clean installation of node dependencies, cache/restore them, build and upload /out folder to Amazon S3
name: shark

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: shark-assets-role
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: AssetsUploadSession
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync . s3://shark-static-site-bucket/
